whoami:
  ingress:
    annotations:
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.middlewares: traefik-traefik-forward-auth@kubernetescrd
    hosts:
    - host: whoami.test.cluster.com
      paths:
      - /
    tls:
    - secretName: whoami-tls
      hosts:
      - whoami.test.cluster.com
