apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmd-rest-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cmd-rest-api
  template:
    metadata:
      labels:
        app: cmd-rest-api
    spec:
      containers:
      - name: cmd-rest-api
        image: docker.io/mdtalham/cmd-rest-api:latest
        ports:
        - containerPort: 8088
          protocol: TCP