apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: whoami
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: whoami
  project: default
  source:
    path: argocd-helm-charts/whoami
    repoURL: git@github.com:Obmondo/k8id.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      - /tmp/git@github.com_obmondo_k8id-config/k8s/test.cluster.com/argocd-apps/values-whoami.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
