apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
  name: velero
  namespace: monitoring
spec:
  groups:
  - name: velero
    rules:
    - alert: VeleroUnsuccessfulBackup
      annotations:
        description: Velero backup was not successful for {{ $labels.schedule }}.
        summary: Velero backup for schedule {{ $labels.schedule }} was unsuccessful.
      expr: |
        ((time() - velero_backup_last_successful_timestamp{schedule=~".*6hrly.*"}) + on(schedule) group_left velero_backup_attempt_total > (60 * 60 * 6) and ON() hour() >= 6.30 <= 18.30) or ((time() - velero_backup_last_successful_timestamp{schedule=~".*daily.*"}) + on(schedule) group_left velero_backup_attempt_total > (60 * 60 * 24) and ON() day_of_week() != 0) or ((time() - velero_backup_last_successful_timestamp{schedule=~".*weekly.*"}) + on(schedule) group_left velero_backup_attempt_total > (60 * 60 * 24 * 7))
      for: 15m
      labels:
        severity: warning
